### ISSUE TITLE
Usable with ILMerge?

### ISSUE THREAD

**Issue by devployment** [config-r/config-r#200]
I'm currently trying to add ConfigR to an internal library project. In general it looks like using ConfigR for getting setting values inside a referenced dll works. 

But in my project I'm using ILMerge to produce a single output dll. If I try to internalize ConfigR (and it's dependencies) I get an exception during runtime containing the following message.

```
C:\_projects\foo\bar\bin\Debug\TestClient.exe.csx(2,1): error CS0122: 'ConfigR.Scripting.ConfigRScriptHost.Add(object)' is inaccessible due to its protection level
```

I'm almost sure that it relates to ILMerge because without merging it looks valid. At least for a very brief test. Any experience using ConfigR together with ILMerge?

**Comment by adamralph** [comment]
The problem arises from the fact that you are internalising ConfigR when you ILMerge it. This means the script cannot call the `Add()` method since it is internal. ILMerge supports the exclusion of specific types from internalisation via a command line option. If you use this to exclude the `ConfigR.Scripting.ConfigRScriptHost` from internalisation then things should work again.

For an example this is how we do this for FakeItEasy https://github.com/FakeItEasy/FakeItEasy/blob/dbfc0289f2493ee10d0aaf325fdc8734307645b4/Source/FakeItEasy/FakeItEasy.csproj#L567 where the types to be excluded are defined in this file https://github.com/FakeItEasy/FakeItEasy/blob/dbfc0289f2493ee10d0aaf325fdc8734307645b4/Source/ILMerge.Internalize.Exclude.txt. We are embedding the execution of ILMerge in our csproj file but the same principle applies however you invoking ILMerge.exe.

**Comment by devployment** [comment]
Thanks for the fast reply. Added `ConfigR.Scripting.ConfigRScriptHost` to the exclusion list. Now I get a different message

`{"Attempt by method 'Submission#0..ctor(Roslyn.Scripting.Session, System.Object ByRef)' to access method 'Microsoft.CSharp.RuntimeHelpers.SessionHelpers.SetSubmission(Roslyn.Scripting.Session, Int32, System.Object)' failed."}`

Another good tip on this one? :)

**Comment by adamralph** [comment]
Nothing really springs to mind right now :confused:.

This may well be the first ever attempt to ILMerge ConfigR :stuck_out_tongue:

**Comment by adamralph** [comment]
@devployment did you manage to get this working in the end?
