### ISSUE TITLE
Remove dependency on JSON.NET

### ISSUE THREAD

**Issue by adamralph** [config-r/config-r#216]
It's only for logging config values so seems silly to take this dependency.

Can probably switch to https://github.com/facebook-csharp-sdk/simple-json or reconsider whether rendering as JSON is really the best idea.

**Comment by cmatskas** [comment]
I could take this on :)

**Comment by cmatskas** [comment]
Do you not take on another dependency if you move away from JSON.NET to simple-json? Is it because of the size of the library? What's the logic behind the change? And if not json for output, what then? pipe-separated key value pairs? I think the transition to Simple-Json should be very simple, as long as you give me the go ahead :)

**Comment by rmbrunet** [comment]
The Logger could handle that. LibLog + Serilog would.

**Comment by adamralph** [comment]
@rmbrunet that is a very good point!

@cmatskas the advantage of Simple-Json is that it is a source package so their would be no transitive dependency. Key-value pairs break down quickly once you consider that the types of config values could be complex with many nested complex property types. (Note that this issue is in regard to the logging of each specific config value, rather than the list of config key-value pairs.)

However, I'm still not sure we should be doing arbitrary structural logging of config values, no matter what mechanism is being used (JSON.NET, Simple-Json, Serilog or otherwise). The only place this is done is trace level logging in the `BasicConfig` class whenever the underlying dictionary is being changed, e.g. https://github.com/config-r/config-r/blob/112ecb7890a84957c7abc26d7a1f955430caf8a1/src/ConfigR/BasicConfig.Dictionary.cs#L42 - if someone were to turn on trace level logging in order to debug some specific config problem then you would expect them to know what values were in their various config sources at that time. The benefit of repeating these values in the trace level log is questionable and it may turn out to be quite costly and verbose in edge cases with very complex types. It may be more sensible to just call `ToString()` on the config value and be done with it.

**Comment by cmatskas** [comment]
I agree,


Should we try this then?


Sent by Outlook for Android





On Tue, Oct 20, 2015 at 11:20 AM -0700, "Adam Ralph" <notifications@github.com> wrote:












@rmbrunet that is a very good point!



@cmatskas the advantage of Simple-Json is that it is a source package so their would be no transitive dependency. Key-value pairs break down quickly once you consider that the types of config values could be complex with many nested complex property types. (Note that this issue is in regard to the logging of each specific config value, rather than the list of config key-value pairs.)



However, I'm still not sure we should be doing arbitrary structural logging of config values, no matter what mechanism is being used (JSON.NET, Simple-Json, Serilog or otherwise). The only place this is done is trace level logging in the BasicConfig class whenever the underlying dictionary is being changed, e.g. https://github.com/config-r/config-r/blob/112ecb7890a84957c7abc26d7a1f955430caf8a1/src/ConfigR/BasicConfig.Dictionary.cs#L42 - if someone were to turn on trace level logging in order to debug some specific config problem then you would expect them to know what values were in their various config sources at that time. The benefit of repeating these values in the trace level log is questionable and it may turn out to be quite costly and verbose in edge cases with very complex types. It may be more sensible to just call 
 ToString() on the config value and be done with it.

**Comment by adamralph** [comment]
@cmatskas yep, :shipit:

**Comment by cmatskas** [comment]
Awesome. I'm on it. ETA tomorrow morning :)

On Tue, Oct 20, 2015 at 7:33 PM, Adam Ralph <notifications@github.com>
wrote:

> @cmatskas <https://github.com/cmatskas> yep, [image: :shipit:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/config-r/config-r/issues/216#issuecomment-149658381>.
>



-- 
Christos Matskas
IT Director
SoftwareLounge

**Comment by adamralph** [comment]
https://www.nuget.org/packages/ConfigR/0.14.0
https://github.com/config-r/config-r/releases/tag/0.14.0
https://twitter.com/adamralph/status/720884248266211329

Thanks @cmatskas, look out for your name in the release notes! :trophy:
